language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script: "echo 'Ready to test'"
script:
  - npm test
after_success:
  - npm run coverage
  - "echo 'Tests complete'"
before_deploy: "echo 'Ready to deploy'"
